### ISSUE TITLE
Keep identical multiple selections matching

### ISSUE THREAD

**Issue by mikey-unfk** [dwarburt/vscode-scramble#9]
When this extension is run with the same string selected more than once (multiple cursors, or "Select All Occurrences of Find Match", etc.), it would be nice to replace all selected occurrences with the same scrambled output.

This could be a new command, in order not to introduce a breaking change -- and maybe there are scenarios in which this would be unwanted?

Let's say you have an API response, and you want to document the shape. Some values are repeated. With the current behavior, it's no longer clear they once had the same value.

PS: Thank you!

**Comment by dwarburt** [comment]
Closing this so we can re open it differently
